name: bulma_sass_example
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: indie <email@example.com>

environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  bulma_sass: 0.6.2+1

dev_dependencies:
  browser: ^0.10.0
  build_runner: ^0.7.10+1
  sass_builder: ^1.1.2
  build_web_compilers: 0.3.0
  dart_to_js_script_rewriter: ^1.0.1
